FROM python:3.6.1-alpine
RUN apt update
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
COPY ./requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
ENV PYTHONUNBUFFERED 1
COPY . .

######################################################################################################

FROM node:16
WORKDIR /usr/src/app
COPY . .
RUN npm cache clean --force
RUN npm install -g npm@8.16.0
RUN npm install --legacy-peer-deps
RUN npm install sanitize.css csstools/normalize.css  --legacy-peer-deps
RUN npm run build
EXPOSE 3000
CMD [ "npm", "run", "start" ]

###################################################################################################

FROM python:3.7.3-stretch

## Step 1:
# Create a working directory
WORKDIR /app
## Step 2:
# Copy source code to working directory
#COPY requirements.txt /app/
COPY . .
## Step 3:
# Install packages from requirements.txt
# hadolint ignore=DL3013
RUN pip install --upgrade pip
RUN pip install --requirement /app/requirements.txt

## Step 4:
# Expose port 80
EXPOSE 80

## Step 5:
# Run app.py at container launch
CMD [ "python3", "app.py" ]

#######################################################################################################


